# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fifthCase(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    self.driver.find_element(By.ID, "username").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("pepe")
    self.driver.find_element(By.ID, "password").send_keys("pepe1234")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.text_to_be_present_in_element((By.CSS_SELECTOR, ".errorMessage"), "Invalid username and password."))
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
  def test_firstCase(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_secondCase(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    assert self.driver.find_element(By.LINK_TEXT, "Home").text == "Home"
    assert self.driver.find_element(By.LINK_TEXT, "Join").text == "Join"
    assert self.driver.find_element(By.LINK_TEXT, "Directory").text == "Directory"
    assert self.driver.find_element(By.LINK_TEXT, "Admin").text == "Admin"
    assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight1 > h4").text == "Teton Elementary"
    assert self.driver.find_element(By.CSS_SELECTOR, ".spotlight2 > h4").text == "Teton Post Office"
    assert self.driver.find_element(By.LINK_TEXT, "Join Us").text == "Join Us"
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    elements = self.driver.find_elements(By.ID, "content")
    assert len(elements) > 0
  
  def test_thirdCase(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Directory").click()
    assert self.driver.find_element(By.ID, "directory-grid").text == "GRID"
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(1) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(2) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(3) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(4) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(5) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(6) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(7) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, "section:nth-child(8) > img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_fourthCase(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "Join").click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").send_keys("Jonathan")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("Uribe")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("Jonathan Store")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("Owner")
    self.driver.find_element(By.NAME, "submit").click()
    element = self.driver.find_element(By.NAME, "email")
    assert element.is_enabled() is True
  
